/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Guides documentation sidebar
  guides: [{ type: 'autogenerated', dirName: '.' }],

  // API documentation sidebars
  'customer-api': [{ type: 'autogenerated', dirName: '.' }],
  'partner-api': [{ type: 'autogenerated', dirName: '.' }],

  // Webhooks documentation sidebars
  'webhooks-latest': [{ type: 'autogenerated', dirName: '.' }],
  'webhooks-legacy': [{ type: 'autogenerated', dirName: '.' }],

  // Integration documentation sidebar
  'integration': [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
